[gcp_service_account]
type = "service_account"
project_id = "gen-lang-client-0977677370"
private_key_id = "c3e1b50e9ab5ce6e2b440ca30af8ad615df22d16"
private_key = "-----BEGIN PRIVATE KEY-----\\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCXyNWqTlCwkRpV\\npcWjJ2MiqNySKpDU6BVd48Tkgz3Bshh3dOmZ4CNZPjLREoU6tD8AG0IkyGPZ4bbN\\n...restante...\\n-----END PRIVATE KEY-----\\n"
client_email = "scolex-test@gen-lang-client-0977677370.iam.gserviceaccount.com"
client_id = "118053652855380945724"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/scolex-test%40gen-lang-client-0977677370.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
